# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_alpr.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1356, 890)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(30, 60, 441, 421))
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frame.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.frame.setAcceptDrops(False)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 121, 16))
        self.label_9.setObjectName("label_9")
        self.DispLb = QtWidgets.QLabel(self.frame)
        self.DispLb.setGeometry(QtCore.QRect(10, 40, 401, 341))
        self.DispLb.setAutoFillBackground(False)
        self.DispLb.setStyleSheet("background-color: rgb(215, 221, 255);")
        self.DispLb.setText("")
        self.DispLb.setScaledContents(True)
        self.DispLb.setObjectName("DispLb")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(30, 500, 561, 211))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 72, 15))
        self.label_3.setObjectName("label_3")
        self.result_form = QtWidgets.QPlainTextEdit(self.frame_2)
        self.result_form.setGeometry(QtCore.QRect(10, 30, 521, 161))
        self.result_form.setAutoFillBackground(False)
        self.result_form.setStyleSheet("background-color: rgb(215, 221, 255);\n"
"font: 14pt \"Arial\";")
        self.result_form.setObjectName("result_form")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(870, 640, 251, 71))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 111, 16))
        self.label_5.setObjectName("label_5")
        self.pr_loc = QtWidgets.QLabel(self.frame_3)
        self.pr_loc.setGeometry(QtCore.QRect(20, 30, 181, 41))
        self.pr_loc.setStyleSheet("background-color: rgb(215, 221, 255);\n"
"font: 14pt \"Arial\";")
        self.pr_loc.setText("")
        self.pr_loc.setObjectName("pr_loc")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(30, 10, 831, 41))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(30, 0, 481, 33))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(490, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_10.setObjectName("label_10")
        self.pattle = QtWidgets.QLabel(self.frame_4)
        self.pattle.setGeometry(QtCore.QRect(580, 10, 81, 21))
        self.pattle.setStyleSheet("background-color: rgb(215, 221, 255);\n"
"font: 12pt \"Axure Handwriting\";")
        self.pattle.setText("")
        self.pattle.setObjectName("pattle")
        self.car_debool = QtWidgets.QRadioButton(self.frame_4)
        self.car_debool.setGeometry(QtCore.QRect(680, 10, 115, 19))
        self.car_debool.setObjectName("car_debool")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(870, 330, 471, 331))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 101, 16))
        self.label_7.setObjectName("label_7")
        self.car_det = QtWidgets.QLabel(self.frame_7)
        self.car_det.setGeometry(QtCore.QRect(20, 30, 401, 271))
        self.car_det.setStyleSheet("background-color: rgb(215, 221, 255);\n"
"font: 14pt \"Arial\";")
        self.car_det.setText("")
        self.car_det.setObjectName("car_det")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(870, 0, 481, 331))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 101, 16))
        self.label_6.setObjectName("label_6")
        self.img_one = QtWidgets.QLabel(self.frame_6)
        self.img_one.setGeometry(QtCore.QRect(20, 30, 401, 271))
        self.img_one.setStyleSheet("background-color: rgb(215, 221, 255);")
        self.img_one.setText("")
        self.img_one.setObjectName("img_one")
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(480, 110, 381, 281))
        self.frame_8.setStyleSheet("border-color: rgb(181, 195, 255);\n"
"border-color: rgb(153, 64, 255);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setGeometry(QtCore.QRect(20, 0, 111, 16))
        self.label_8.setObjectName("label_8")
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setGeometry(QtCore.QRect(0, 20, 359, 271))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout.setObjectName("gridLayout")
        self.ColorFm = QtWidgets.QFrame(self.frame_12)
        self.ColorFm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ColorFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ColorFm.setObjectName("ColorFm")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.ColorFm)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.BlueColorSld = QtWidgets.QSlider(self.ColorFm)
        self.BlueColorSld.setMaximum(255)
        self.BlueColorSld.setProperty("value", 255)
        self.BlueColorSld.setOrientation(QtCore.Qt.Horizontal)
        self.BlueColorSld.setObjectName("BlueColorSld")
        self.gridLayout_7.addWidget(self.BlueColorSld, 3, 2, 1, 1)
        self.BlueColorSpB = QtWidgets.QSpinBox(self.ColorFm)
        self.BlueColorSpB.setMaximum(255)
        self.BlueColorSpB.setProperty("value", 255)
        self.BlueColorSpB.setObjectName("BlueColorSpB")
        self.gridLayout_7.addWidget(self.BlueColorSpB, 3, 3, 1, 1)
        self.GreenColorSpB = QtWidgets.QSpinBox(self.ColorFm)
        self.GreenColorSpB.setMaximum(255)
        self.GreenColorSpB.setProperty("value", 255)
        self.GreenColorSpB.setObjectName("GreenColorSpB")
        self.gridLayout_7.addWidget(self.GreenColorSpB, 2, 3, 1, 1)
        self.GreenColorSld = QtWidgets.QSlider(self.ColorFm)
        self.GreenColorSld.setMaximum(255)
        self.GreenColorSld.setProperty("value", 255)
        self.GreenColorSld.setOrientation(QtCore.Qt.Horizontal)
        self.GreenColorSld.setObjectName("GreenColorSld")
        self.gridLayout_7.addWidget(self.GreenColorSld, 2, 2, 1, 1)
        self.RedColorSld = QtWidgets.QSlider(self.ColorFm)
        self.RedColorSld.setMaximum(255)
        self.RedColorSld.setProperty("value", 255)
        self.RedColorSld.setOrientation(QtCore.Qt.Horizontal)
        self.RedColorSld.setObjectName("RedColorSld")
        self.gridLayout_7.addWidget(self.RedColorSld, 1, 2, 1, 1)
        self.RedColorSpB = QtWidgets.QSpinBox(self.ColorFm)
        self.RedColorSpB.setMaximum(255)
        self.RedColorSpB.setProperty("value", 255)
        self.RedColorSpB.setObjectName("RedColorSpB")
        self.gridLayout_7.addWidget(self.RedColorSpB, 1, 3, 1, 1)
        self.RedColorLb = QtWidgets.QLabel(self.ColorFm)
        self.RedColorLb.setMinimumSize(QtCore.QSize(40, 0))
        self.RedColorLb.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"color: rgb(255, 0, 0);")
        self.RedColorLb.setObjectName("RedColorLb")
        self.gridLayout_7.addWidget(self.RedColorLb, 1, 0, 1, 1)
        self.BlueColorLb = QtWidgets.QLabel(self.ColorFm)
        self.BlueColorLb.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"color: rgb(0, 0, 255);")
        self.BlueColorLb.setObjectName("BlueColorLb")
        self.gridLayout_7.addWidget(self.BlueColorLb, 3, 0, 1, 1)
        self.GreenColorLb = QtWidgets.QLabel(self.ColorFm)
        self.GreenColorLb.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"color: rgb(0, 255, 0);")
        self.GreenColorLb.setObjectName("GreenColorLb")
        self.gridLayout_7.addWidget(self.GreenColorLb, 2, 0, 1, 1)
        self.GrayImgCkB = QtWidgets.QCheckBox(self.ColorFm)
        self.GrayImgCkB.setStyleSheet("font: 11pt \"Adobe 黑体 Std R\";")
        self.GrayImgCkB.setObjectName("GrayImgCkB")
        self.gridLayout_7.addWidget(self.GrayImgCkB, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.ColorFm, 0, 0, 1, 2)
        self.ExpTimeLb = QtWidgets.QLabel(self.frame_12)
        self.ExpTimeLb.setStyleSheet("font: 11pt \"Adobe 黑体 Std R\";")
        self.ExpTimeLb.setObjectName("ExpTimeLb")
        self.gridLayout.addWidget(self.ExpTimeLb, 1, 0, 1, 1)
        self.ExpTimeSld = QtWidgets.QSlider(self.frame_12)
        self.ExpTimeSld.setMinimum(-10)
        self.ExpTimeSld.setMaximum(-2)
        self.ExpTimeSld.setOrientation(QtCore.Qt.Horizontal)
        self.ExpTimeSld.setObjectName("ExpTimeSld")
        self.gridLayout.addWidget(self.ExpTimeSld, 1, 1, 1, 1)
        self.ExpTimeSpB = QtWidgets.QSpinBox(self.frame_12)
        self.ExpTimeSpB.setMaximumSize(QtCore.QSize(60, 30))
        self.ExpTimeSpB.setMinimum(-10)
        self.ExpTimeSpB.setMaximum(-2)
        self.ExpTimeSpB.setObjectName("ExpTimeSpB")
        self.gridLayout.addWidget(self.ExpTimeSpB, 1, 2, 1, 1)
        self.GainLb = QtWidgets.QLabel(self.frame_12)
        self.GainLb.setStyleSheet("font: 11pt \"Adobe 黑体 Std R\";")
        self.GainLb.setObjectName("GainLb")
        self.gridLayout.addWidget(self.GainLb, 2, 0, 1, 1)
        self.GainSld = QtWidgets.QSlider(self.frame_12)
        self.GainSld.setMaximum(128)
        self.GainSld.setOrientation(QtCore.Qt.Horizontal)
        self.GainSld.setObjectName("GainSld")
        self.gridLayout.addWidget(self.GainSld, 2, 1, 1, 1)
        self.GainSpB = QtWidgets.QDoubleSpinBox(self.frame_12)
        self.GainSpB.setMaximumSize(QtCore.QSize(60, 30))
        self.GainSpB.setMaximum(128.0)
        self.GainSpB.setObjectName("GainSpB")
        self.gridLayout.addWidget(self.GainSpB, 2, 2, 1, 1)
        self.BrightLb = QtWidgets.QLabel(self.frame_12)
        self.BrightLb.setStyleSheet("font: 11pt \"Adobe 黑体 Std R\";")
        self.BrightLb.setObjectName("BrightLb")
        self.gridLayout.addWidget(self.BrightLb, 3, 0, 1, 1)
        self.BrightSld = QtWidgets.QSlider(self.frame_12)
        self.BrightSld.setMinimum(-64)
        self.BrightSld.setMaximum(64)
        self.BrightSld.setOrientation(QtCore.Qt.Horizontal)
        self.BrightSld.setObjectName("BrightSld")
        self.gridLayout.addWidget(self.BrightSld, 3, 1, 1, 1)
        self.BrightSpB = QtWidgets.QDoubleSpinBox(self.frame_12)
        self.BrightSpB.setMaximumSize(QtCore.QSize(60, 30))
        self.BrightSpB.setMinimum(-64.0)
        self.BrightSpB.setMaximum(64.0)
        self.BrightSpB.setSingleStep(0.01)
        self.BrightSpB.setObjectName("BrightSpB")
        self.gridLayout.addWidget(self.BrightSpB, 3, 2, 1, 1)
        self.ContrastLb = QtWidgets.QLabel(self.frame_12)
        self.ContrastLb.setStyleSheet("font: 11pt \"Adobe 黑体 Std R\";")
        self.ContrastLb.setObjectName("ContrastLb")
        self.gridLayout.addWidget(self.ContrastLb, 4, 0, 1, 1)
        self.ContrastSld = QtWidgets.QSlider(self.frame_12)
        self.ContrastSld.setMinimum(0)
        self.ContrastSld.setMaximum(100)
        self.ContrastSld.setOrientation(QtCore.Qt.Horizontal)
        self.ContrastSld.setObjectName("ContrastSld")
        self.gridLayout.addWidget(self.ContrastSld, 4, 1, 1, 1)
        self.ContrastSpB = QtWidgets.QDoubleSpinBox(self.frame_12)
        self.ContrastSpB.setMaximumSize(QtCore.QSize(60, 30))
        self.ContrastSpB.setMinimum(0.0)
        self.ContrastSpB.setMaximum(100.0)
        self.ContrastSpB.setSingleStep(0.01)
        self.ContrastSpB.setObjectName("ContrastSpB")
        self.gridLayout.addWidget(self.ContrastSpB, 4, 2, 1, 1)
        self.FilePathLb = QtWidgets.QLabel(self.frame_12)
        self.FilePathLb.setStyleSheet("font: 11pt \"Adobe 黑体 Std R\";")
        self.FilePathLb.setObjectName("FilePathLb")
        self.gridLayout.addWidget(self.FilePathLb, 5, 0, 1, 1)
        self.FilePathLE = QtWidgets.QLineEdit(self.frame_12)
        self.FilePathLE.setReadOnly(True)
        self.FilePathLE.setObjectName("FilePathLE")
        self.gridLayout.addWidget(self.FilePathLE, 5, 1, 1, 1)
        self.FilePathBt = QtWidgets.QPushButton(self.frame_12)
        self.FilePathBt.setMaximumSize(QtCore.QSize(60, 30))
        self.FilePathBt.setStyleSheet("font: 11pt \"Adobe 黑体 Std R\";")
        self.FilePathBt.setObjectName("FilePathBt")
        self.gridLayout.addWidget(self.FilePathBt, 5, 2, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setGeometry(QtCore.QRect(480, 400, 381, 80))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.VideoInfoFm = QtWidgets.QFrame(self.frame_9)
        self.VideoInfoFm.setGeometry(QtCore.QRect(0, 10, 361, 60))
        self.VideoInfoFm.setMaximumSize(QtCore.QSize(16777215, 60))
        self.VideoInfoFm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VideoInfoFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VideoInfoFm.setObjectName("VideoInfoFm")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.VideoInfoFm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtWidgets.QLabel(self.VideoInfoFm)
        self.label_13.setStyleSheet("font: 11pt \"Adobe 黑体 Std R\";")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.FmRateLCD = QtWidgets.QLCDNumber(self.VideoInfoFm)
        self.FmRateLCD.setMaximumSize(QtCore.QSize(100, 16777215))
        self.FmRateLCD.setObjectName("FmRateLCD")
        self.horizontalLayout.addWidget(self.FmRateLCD)
        self.label_14 = QtWidgets.QLabel(self.VideoInfoFm)
        self.label_14.setStyleSheet("font: 11pt \"Adobe 黑体 Std R\";")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.ImgWidthLCD = QtWidgets.QLCDNumber(self.VideoInfoFm)
        self.ImgWidthLCD.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ImgWidthLCD.setObjectName("ImgWidthLCD")
        self.horizontalLayout.addWidget(self.ImgWidthLCD)
        self.ImgHeightLCD = QtWidgets.QLCDNumber(self.VideoInfoFm)
        self.ImgHeightLCD.setObjectName("ImgHeightLCD")
        self.horizontalLayout.addWidget(self.ImgHeightLCD)
        self.frame_10 = QtWidgets.QFrame(self.centralwidget)
        self.frame_10.setGeometry(QtCore.QRect(610, 730, 761, 81))
        self.frame_10.setStyleSheet("background-color: rgb(238, 233, 255);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_11 = QtWidgets.QLabel(self.frame_10)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 72, 15))
        self.label_11.setObjectName("label_11")
        self.remove_file = QtWidgets.QPushButton(self.frame_10)
        self.remove_file.setGeometry(QtCore.QRect(590, 0, 93, 28))
        self.remove_file.setStyleSheet("background-color: rgb(230, 240, 255);")
        self.remove_file.setObjectName("remove_file")
        self.export_exl = QtWidgets.QPushButton(self.frame_10)
        self.export_exl.setGeometry(QtCore.QRect(480, 0, 93, 28))
        self.export_exl.setStyleSheet("background-color: rgb(230, 240, 255);")
        self.export_exl.setObjectName("export_exl")
        self.RecordBt = QtWidgets.QPushButton(self.frame_10)
        self.RecordBt.setGeometry(QtCore.QRect(470, 40, 220, 28))
        self.RecordBt.setStyleSheet("background-color: rgb(230, 240, 255);")
        self.RecordBt.setObjectName("RecordBt")
        self.StopBt = QtWidgets.QPushButton(self.frame_10)
        self.StopBt.setGeometry(QtCore.QRect(240, 40, 221, 28))
        self.StopBt.setStyleSheet("background-color: rgb(230, 240, 255);")
        self.StopBt.setObjectName("StopBt")
        self.ShowBt = QtWidgets.QPushButton(self.frame_10)
        self.ShowBt.setGeometry(QtCore.QRect(10, 40, 220, 28))
        self.ShowBt.setStyleSheet("background-color: rgb(230, 240, 255);")
        self.ShowBt.setObjectName("ShowBt")
        self.frame_11 = QtWidgets.QFrame(self.centralwidget)
        self.frame_11.setGeometry(QtCore.QRect(610, 530, 221, 121))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_12 = QtWidgets.QLabel(self.frame_11)
        self.label_12.setGeometry(QtCore.QRect(20, 30, 72, 15))
        self.label_12.setObjectName("label_12")
        self.pr_res = QtWidgets.QLabel(self.frame_11)
        self.pr_res.setGeometry(QtCore.QRect(30, 50, 181, 61))
        self.pr_res.setStyleSheet("background-color: rgb(215, 221, 255);\n"
"font: 18pt \"Arial\";\n"
"\n"
"")
        self.pr_res.setObjectName("pr_res")
        self.MsgTE = QtWidgets.QTextEdit(self.centralwidget)
        self.MsgTE.setGeometry(QtCore.QRect(40, 750, 521, 56))
        self.MsgTE.setStyleSheet("background-color: rgb(215, 221, 255);\n"
"font: 14pt \"Arial\";")
        self.MsgTE.setReadOnly(True)
        self.MsgTE.setObjectName("MsgTE")
        self.img_pat = QtWidgets.QPushButton(self.centralwidget)
        self.img_pat.setGeometry(QtCore.QRect(732, 60, 101, 28))
        self.img_pat.setStyleSheet("background-color: rgb(230, 240, 255);")
        self.img_pat.setObjectName("img_pat")
        self.vid_pat = QtWidgets.QPushButton(self.centralwidget)
        self.vid_pat.setGeometry(QtCore.QRect(610, 60, 101, 28))
        self.vid_pat.setStyleSheet("background-color: rgb(230, 240, 255);")
        self.vid_pat.setObjectName("vid_pat")
        self.cam_pat = QtWidgets.QPushButton(self.centralwidget)
        self.cam_pat.setGeometry(QtCore.QRect(490, 60, 93, 28))
        self.cam_pat.setStyleSheet("background-color: rgb(230, 240, 255);")
        self.cam_pat.setObjectName("cam_pat")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1356, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # self.setWindowFlag(QtCore.Qt.FramelessWindowHint)  # 隐藏边框

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "my_alpr"))
        self.label_9.setText(_translate("MainWindow", "摄像头实时显示"))
        self.label_3.setText(_translate("MainWindow", "识别记录"))
        self.label_5.setText(_translate("MainWindow", "车牌校正及定位"))
        self.label.setText(_translate("MainWindow", "无约束场景全自动车牌识别系统"))
        self.label_10.setText(_translate("MainWindow", "识别模式"))
        self.car_debool.setText(_translate("MainWindow", "开启车辆检测"))
        self.label_7.setText(_translate("MainWindow", "车辆检测结果"))
        self.label_6.setText(_translate("MainWindow", "单帧图像"))
        self.label_8.setText(_translate("MainWindow", "调节摄像头参数"))
        self.RedColorLb.setText(_translate("MainWindow", "R"))
        self.BlueColorLb.setText(_translate("MainWindow", "B"))
        self.GreenColorLb.setText(_translate("MainWindow", "G"))
        self.GrayImgCkB.setText(_translate("MainWindow", "Gray"))
        self.ExpTimeLb.setText(_translate("MainWindow", "曝光时间："))
        self.GainLb.setText(_translate("MainWindow", "增益："))
        self.BrightLb.setText(_translate("MainWindow", "亮度："))
        self.ContrastLb.setText(_translate("MainWindow", "对比度："))
        self.FilePathLb.setText(_translate("MainWindow", "文件路径："))
        self.FilePathBt.setText(_translate("MainWindow", "…"))
        self.label_13.setText(_translate("MainWindow", "帧频："))
        self.label_14.setText(_translate("MainWindow", "尺寸："))
        self.label_11.setText(_translate("MainWindow", "控制按钮"))
        self.remove_file.setText(_translate("MainWindow", "清除缓存"))
        self.export_exl.setText(_translate("MainWindow", "导出记录到"))
        self.RecordBt.setText(_translate("MainWindow", "保存"))
        self.StopBt.setText(_translate("MainWindow", "暂停"))
        self.ShowBt.setText(_translate("MainWindow", "开始"))
        self.label_12.setText(_translate("MainWindow", "识别结果"))
        self.pr_res.setText(_translate("MainWindow", "车牌号"))
        self.img_pat.setText(_translate("MainWindow", "单张图像模式"))
        self.vid_pat.setText(_translate("MainWindow", "视频识别模式"))
        self.cam_pat.setText(_translate("MainWindow", "摄像头模式"))
